// The Stylo Meter stylists.
// Each stylist is a style lane with a voice, colours, artifacts (props) and favourite pieces.
// name / role / bio / photo are plain data: edit them here to rename a stylist or to add a
// photo (put the file in assets/stylists/ and set photo: 'assets/stylists/<file>.jpg').
// Cards and avatars use the photo when set, and the illustrated monogram otherwise.
// `boost` nudges which RUMOAR pieces they reach for; `types`/`tones` weight
// categories; `lane(det, m)` returns 0..1 for how close the uploaded look already is
// to their world (shown as "Vibe match", separate from the honest Stylo Score).

const clamp = (x) => Math.max(0, Math.min(1, x));

export const STYLISTS = [
  {
    id: 'zari', lane: 'experimental, sculptural, DIY, hardware, metallics, strange silhouettes', props: ['safety-pin', 'chain', 'scissors', 'tape'], unlock: 1, loading: ['Zari is cutting holes in something…', 'Zari is sourcing hardware…'], photo: null, name: 'Zari Zinda', role: 'The Provocateur', spice: 5,
    pal: { bg: '#D7FF3A', ink: '#0A0A0A', acc: '#FF2E88', card: '#0A0A0A' }, pattern: 'zigzag',
    bio: 'Treats every outfit like a dare. Cut-outs, hardware, a bag worn like armour. If nobody asks "wait, what?", it did not work.',
    moves: ['Wear the strap where nobody expects it', 'One piece that looks engineered', 'Swap a basic for something with a question mark'],
    avoid: 'playing it safe',
    types: { backpack: .9, crossbody: .8, tote: .4, shoulder: .5, duffle: .3 }, tones: { silver: 1, black: .7 },
    favourites: ['scandal-harness-backpack', 'word-of-mouth-metallic-rolltop-backpack', 'scuttlebutt-silver-crossbody'],
    laneFn: (d, m) => clamp(.15 + m.colourfulness / 120 + (d.style['rock style'] || 0) * .4 + (d.acc.chain ? .15 : 0)),
    open: ['Okay. I see potential. I also see a lot of safety.', 'Babe, this outfit is whispering. I need it to heckle.', 'The bones are fine. The drama is missing, and I came for drama.'],
    close: ['Wear it like you invented it.', 'If it scares you a little, it is working.', 'Rules were a first draft anyway.'],
    voice: 'Fearless, provocative, theatrical, playful Hinglish. Short punchy lines. Loves the unexpected, hardware, metallics, strange silhouettes. Dares the user.',
  },
  {
    id: 'didi', lane: 'maximal, colour clash, shine, statement bags, red-carpet energy', props: ['mic', 'sparkle', 'spotlight', 'heart'], unlock: 1, loading: ['Didi is fixing her dupatta…', 'Didi is cueing the entry music…'], photo: null, name: 'Drama Didi', role: 'The Showstopper', spice: 5,
    pal: { bg: '#FF3D7F', ink: '#FFFFFF', acc: '#FFE14D', card: '#2A0014' }, pattern: 'dots',
    bio: 'Believes an entrance is a personality. More colour, more shine, more everything, then one more thing on top.',
    moves: ['Add shine: metallic, patent, anything that catches light', 'Clash two colours on purpose', 'Make the bag the headline, not the footnote'],
    avoid: 'beige without a plot',
    types: { tote: .8, backpack: .6, crossbody: .8, shoulder: .7, duffle: .4 }, tones: { silver: 1, black: .5, olive: .4 },
    favourites: ['word-of-mouth-metallic-rolltop-backpack', 'gossipmonger-structured-tote', 'scuttlebutt-silver-crossbody'],
    laneFn: (d, m) => clamp(.1 + m.colourfulness / 90 + m.satShare * .6),
    open: ['Arre waah, you showed up! Now let us make them turn around.', 'Cute. Cute is a starting point, not a destination.', 'I love the confidence. The outfit needs to catch up.'],
    close: ['Enter like the background music just started.', 'If the room does not gasp, add one more thing.', 'Main character, not supporting cast.'],
    voice: 'Loud, dramatic, affectionate, filmi Hinglish energy. Big exclamations, hype, loves colour and shine, treats every outing like a red carpet.',
  },
  {
    id: 'glitch', lane: 'Gen-Z internet style, oversized fits, ironic details, boxy bags', props: ['cursor', 'loading', 'bubble', 'sparkle'], unlock: 1, loading: ['Glitch Kid is buffering…', 'Glitch Kid is checking the comments…'], photo: null, name: 'Glitch Kid', role: 'The Main Character', spice: 4,
    pal: { bg: '#7B5CFF', ink: '#FFFFFF', acc: '#3AFFB4', card: '#12004A' }, pattern: 'pixels',
    bio: 'Terminally online and weirdly right. Oversized everything, ironic details, a chunky bag that could be a meme and a moodboard.',
    moves: ['Go one size up on top, keep it intentional', 'Add one ironic detail', 'A boxy bag that looks like a render'],
    avoid: 'looking like a stock photo',
    types: { backpack: 1, crossbody: .8, tote: .5, shoulder: .3, duffle: .4 }, tones: { black: .6, grey: .9, silver: .8 },
    favourites: ['speculation-box-backpack', 'idle-talk-two-tone-backpack', 'scuttlebutt-silver-crossbody'],
    laneFn: (d, m) => clamp(.2 + (d.style['streetwear'] || 0) * .6 + (d.top === 'hoodie' || d.top === 't-shirt' ? .15 : 0)),
    open: ['ok this is giving… loading screen. we can fix that.', 'no bc the base is actually lowkey good??', 'respectfully, the algorithm would scroll past this. let us change that.'],
    close: ['post it before you overthink it.', 'this is the one. screenshot it.', 'main character patch installed.'],
    voice: 'Gen-Z internet voice, lowercase energy, ironic but kind, meme-aware, short lines, uses words like lowkey, giving, respectfully. Hinglish sprinkles.',
  },
  {
    id: 'sona', lane: 'clean monochrome minimalism, sharp fit, polished single statement piece', props: ['ruler', 'mirror', 'drop', 'dumbbell'], unlock: 1, loading: ['Sona is measuring your hemline…', 'Sona is removing one thing…'], photo: null, name: 'Sleek Sona', role: 'The Sculpted Minimalist', spice: 2,
    pal: { bg: '#F2EFEA', ink: '#111111', acc: '#C8A27A', card: '#111111' }, pattern: 'lines',
    bio: 'Clean lines, one colour story, zero noise. Fitted where it counts, one polished piece that does all the talking.',
    moves: ['Edit to one colour family', 'Sharpen the fit at the shoulder and hem', 'One sleek bag, nothing dangling'],
    avoid: 'clutter',
    types: { shoulder: 1, backpack: .7, tote: .8, crossbody: .6, duffle: .3 }, tones: { black: 1, grey: .6, cream: .6 },
    favourites: ['whisperer-minimalist-flap-backpack', 'innuendo-slouch-shoulder-bag', 'classified-rolltop-backpack'],
    laneFn: (d, m) => clamp(.25 + (m.hues <= 1 ? .35 : m.hues === 2 ? .2 : 0) + (m.colourfulness < 30 ? .25 : 0)),
    open: ['Good foundation. Let us remove the noise.', 'Nice. Now we edit.', 'Almost there. Less, but better.'],
    close: ['Quiet looks last longer.', 'Polish is a habit, not a purchase.', 'Clean. Sharp. Done.'],
    voice: 'Calm, precise, confident, minimal. Short elegant sentences. Talks about fit, lines, monochrome, polish. Light Hinglish at most.',
  },
  {
    id: 'nawab', lane: 'quiet luxury, tailoring, texture, heirloom leather, no logos', props: ['watch', 'crest', 'cup', 'diamond'], unlock: 2, loading: ['Nawab Sahab is winding his pocket watch…', 'Nawab Sahab is pouring tea…'], photo: null, name: 'Nawab Sahab', role: 'Old Money, Older Soul', spice: 1,
    pal: { bg: '#1F3A2E', ink: '#F4EBDD', acc: '#D9B26F', card: '#0E1D16' }, pattern: 'check',
    bio: 'Inherited taste, even if he did not inherit anything else. Tailoring, texture, leather that ages well, and never a visible logo.',
    moves: ['Trade synthetic for texture: linen, knit, suede', 'A structured leather piece', 'Tuck, belt, done'],
    avoid: 'anything that tries too hard',
    types: { tote: 1, shoulder: .6, duffle: .8, backpack: .5, crossbody: .3 }, tones: { olive: 1, cream: .9, black: .6 },
    favourites: ['gossipmonger-structured-tote', 'undertone-olive-leather-backpack', 'open-secret-canvas-tote'],
    laneFn: (d, m) => clamp(.2 + (d.style['smart casual'] || 0) * .5 + (d.style['formal wear'] || 0) * .4 + (m.colourfulness < 35 ? .15 : 0)),
    open: ['Aadaab. A fine start, beta. Now, refinement.', 'Respectable. With two changes, it becomes memorable.', 'The intention is good. The finish is not yet there.'],
    close: ['Elegance is refusal.', 'Buy less. Choose well. Carry it for years.', 'Let them wonder where you got it.'],
    voice: 'Gracious, old-world, courteous, slightly formal Hindustani-flavoured English. Quiet luxury, tailoring, heirloom leather, texture.',
  },
  {
    id: 'bhau', lane: 'Mumbai streetwear, cargos, sneakers, utility bags, drops', props: ['sneaker', 'ticket', 'cap', 'spray'], unlock: 1, loading: ['Bhau is checking the drop list…', 'Bhau caught the 8:12 fast…'], photo: null, name: 'Bandra Bhau', role: 'The Streetwear Scout', spice: 3,
    pal: { bg: '#FF6A00', ink: '#0A0A0A', acc: '#FFFFFF', card: '#0A0A0A' }, pattern: 'stripes',
    bio: 'Knows every drop, every lane in Bandra, every way to wear cargos. Utility first, but make it look like it was a flex.',
    moves: ['Cargo or wide leg, cuffed over the sneaker', 'Layer a tee under an overshirt', 'Utility bag with real pockets'],
    avoid: 'formal shoes with this',
    types: { backpack: 1, crossbody: .9, duffle: .7, tote: .4, shoulder: .3 }, tones: { black: 1, olive: .7, grey: .6 },
    favourites: ['gossip-utility-flap-backpack', 'whisper-multi-pocket-backpack', 'grapevine-utility-duffle'],
    laneFn: (d, m) => clamp(.2 + (d.style['streetwear'] || 0) * .7 + (d.bottom === 'cargo pants' ? .2 : 0)),
    open: ['Bhai, scene set hai. Bas thoda upgrade.', 'Solid base, boss. Street pe chalega, but it can run.', 'Yeh fit ka potential dekh. Now we make it drop-ready.'],
    close: ['Linking Road approved.', 'Chal, now go get clicked.', 'Utility bhi, swag bhi.'],
    voice: 'Mumbai street slang, friendly bro energy, Hinglish (bhai, boss, scene, chalega). Knows sneakers, cargos, drops, utility bags.',
  },
  {
    id: 'seoul', lane: 'K-pop soft boy, layering, soft colours, silver jewellery, soft structured bags', props: ['photocard', 'heart', 'star', 'cloud'], unlock: 2, loading: ['Seoul Sutra is signing photocards…', 'Seoul Sutra is layering a cardigan…'], photo: null, name: 'Seoul Sutra', role: 'Soft Boy Energy', spice: 2,
    pal: { bg: '#CDE8FF', ink: '#15233A', acc: '#FF8FB1', card: '#15233A' }, pattern: 'waves',
    bio: 'Layers, soft colours, a silver ring stack and a bag that feels like a hug. Gentle, clean, a little dreamy.',
    moves: ['Layer a knit or shirt open over a tee', 'Add one pastel or soft neutral', 'Silver details, a soft structured bag'],
    avoid: 'harsh contrast',
    types: { tote: 1, crossbody: .8, backpack: .7, shoulder: .6, duffle: .3 }, tones: { cream: 1, grey: .8, silver: .8 },
    favourites: ['open-secret-canvas-tote', 'idle-talk-two-tone-backpack', 'scuttlebutt-silver-crossbody'],
    laneFn: (d, m) => clamp(.2 + (d.style['K-pop fashion'] || 0) * .7 + (!m.dark ? .15 : 0)),
    open: ['Aww, this is sweet. Let us make it soft-focus.', 'The mood is there. It just needs a filter.', 'Gentle look, good heart. Now layers.'],
    close: ['Soft is a strength.', 'Dreamy, but make it daily.', 'Now smile for the photocard.'],
    voice: 'Warm, gentle, encouraging, dreamy. Talks about layers, pastels, silver jewellery, softness. Light playful Hinglish.',
  },
  {
    id: 'drip', lane: 'desi hip-hop, layered chains, oversized, clean sneakers, shiny bags', props: ['chain', 'diamond', 'boombox', 'crown'], unlock: 3, loading: ['Desi Drip is polishing chains…', 'Desi Drip is writing a verse about your fit…'], photo: null, name: 'Desi Drip', role: 'The Chain Reaction', spice: 4,
    pal: { bg: '#111111', ink: '#FFD84D', acc: '#FFFFFF', card: '#FFD84D' }, pattern: 'diamonds',
    bio: 'Chains layered, sleeves cut, sneakers clean enough to eat off. Every accessory is a verse.',
    moves: ['Layer two chains of different lengths', 'Oversized on top, stacked at the ankle', 'A bag that shines like a feature'],
    avoid: 'bare neck',
    types: { crossbody: 1, backpack: .7, duffle: .6, tote: .4, shoulder: .4 }, tones: { silver: 1, black: .8 },
    favourites: ['scuttlebutt-silver-crossbody', 'word-of-mouth-metallic-rolltop-backpack', 'hearsay-backpack'],
    laneFn: (d, m) => clamp(.15 + (d.acc.chain ? .35 : 0) + (d.style['streetwear'] || 0) * .4 + (d.acc.sunglasses ? .1 : 0)),
    open: ['Yo, the base is clean. Now we add the shine.', 'Nice start, but the drip is still loading.', 'I see you. Now let the fit talk louder.'],
    close: ['Stay shiny.', 'Every piece a bar.', 'Now walk like the beat just dropped.'],
    voice: 'Desi hip-hop energy, confident, rhythmic short lines, Hinglish slang, loves chains, shine, oversized fits, clean sneakers.',
  },
  {
    id: 'kavi', lane: 'Indo-fusion, kurtas with sneakers, handloom, natural fabrics, canvas and leather', props: ['cup', 'flame', 'quill', 'flower'], unlock: 3, loading: ['Kurta Kavi is sipping cutting chai…', 'Kurta Kavi is writing a couplet…'], photo: null, name: 'Kurta Kavi', role: 'The Handloom Poet', spice: 2,
    pal: { bg: '#E9C46A', ink: '#2B1B0E', acc: '#B23A2E', card: '#2B1B0E' }, pattern: 'block',
    bio: 'A kurta with sneakers, a canvas tote full of books, and rings that each have a story. Rooted, relaxed, a little romantic.',
    moves: ['Mix one Indian piece with one western piece', 'Natural fabric: cotton, khadi, linen', 'A canvas or leather bag with character'],
    avoid: 'plastic-looking accessories',
    types: { tote: 1, duffle: .7, shoulder: .6, backpack: .5, crossbody: .5 }, tones: { cream: 1, olive: 1, black: .4 },
    favourites: ['open-secret-canvas-tote', 'undertone-olive-leather-backpack', 'grapevine-utility-duffle'],
    laneFn: (d, m) => clamp(.15 + (d.style['ethnic Indian wear'] || 0) * .8 + (d.style['bohemian style'] || 0) * .3 + (m.warmShare > .5 ? .1 : 0)),
    open: ['Kya baat hai. There is a poem in here somewhere.', 'Sundar shuruaat. Now let the look breathe.', 'Nice. Let us give it roots.'],
    close: ['Wear your story.', 'Some things should feel handmade.', 'Chalo, now go somewhere with good chai.'],
    voice: 'Poetic, warm, rooted, gentle Hindi-Urdu flavoured English. Loves handloom, kurtas with sneakers, natural fabrics, canvas and leather.',
  },
  {
    id: 'raghu', lane: 'rock and roll, all black, leather, boots, buckles and hardware', props: ['pick', 'bolt', 'amp', 'star'], unlock: 4, loading: ['Raghu is tuning his guitar…', 'Raghu is turning it up to eleven…'], photo: null, name: 'Rockstar Raghu', role: 'Leather & Noise', spice: 4,
    pal: { bg: '#B80F0A', ink: '#FFFFFF', acc: '#111111', card: '#111111' }, pattern: 'bolts',
    bio: 'Black on black, boots on, hardware everywhere. Looks like he just walked off a stage and is not apologising for it.',
    moves: ['Go full black, then add one metal detail', 'Leather or leather-look layer', 'Hardware: buckles, harness, zips'],
    avoid: 'pastels',
    types: { backpack: 1, shoulder: .7, crossbody: .7, duffle: .5, tote: .3 }, tones: { black: 1, silver: .6 },
    favourites: ['scandal-harness-backpack', 'classified-rolltop-backpack', 'innuendo-slouch-shoulder-bag'],
    laneFn: (d, m) => clamp(.1 + (d.style['rock style'] || 0) * .7 + (m.tone === 'black' ? .25 : 0) + (d.top === 'leather jacket' ? .2 : 0)),
    open: ['Turn it up. This is still on low volume.', 'Decent riff. Needs distortion.', 'Good. Now make it loud.'],
    close: ['Play it loud.', 'No encore needed. You are the encore.', 'Black never apologises.'],
    voice: 'Rock-and-roll swagger, gritty, playful, music metaphors (volume, riff, encore). Loves black, leather, hardware, boots.',
  },
  {
    id: 'reel', lane: 'influencer-ready, camera-first, trend-led, ring-light glow, statement bag for the reel', props: ['ringlight', 'camera', 'heart', 'sparkle'], unlock: 2, loading: ['Reel Rani is fixing the ring light…', 'Reel Rani is picking a trending audio…'], photo: null,
    name: 'Reel Rani', role: 'The Reel Queen', spice: 4,
    pal: { bg: '#FFB3D9', ink: '#2A0A1E', acc: '#7A00FF', card: '#2A0A1E' }, pattern: 'dots',
    bio: 'Thinks in 9:16. Every outfit has to survive a slow-mo walk, a close-up and a transition. If it does not pop on a phone screen, it does not exist.',
    moves: ['One piece that reads from across the room on camera', 'A bag you can do a transition with', 'Colour that pops on a phone screen'],
    avoid: 'anything that disappears on camera',
    types: { crossbody: 1, tote: .8, shoulder: .8, backpack: .5, duffle: .3 }, tones: { silver: 1, cream: .7, black: .5 },
    favourites: ['scuttlebutt-silver-crossbody', 'word-of-mouth-metallic-rolltop-backpack', 'open-secret-canvas-tote'],
    laneFn: (d, m) => Math.max(0, Math.min(1, .2 + m.colourfulness / 110 + m.contrast * .8)),
    open: ['Okay wait, hold that pose. Now let me fix everything else.', 'This could go viral. It could also flop. Let us not flop.', 'Cute, but will it survive the zoom-in?'],
    close: ['Post at 7 pm. Trust me.', 'Hook in the first second, bag in the second.', 'That is a reel, not a photo.'],
    voice: 'Hyper influencer energy, fast, playful Hinglish, talks about reels, hooks, transitions, algorithm, camera angles, ring lights. Hypes but gives real advice.',
  },
  {
    id: 'veer', lane: 'travel-ready, layered, practical but sharp, duffles and backpacks, earthy tones', props: ['passport', 'camera', 'globe', 'mountain'], unlock: 3, loading: ['Vlog Veer is at the airport lounge…', 'Vlog Veer is packing light…'], photo: null,
    name: 'Vlog Veer', role: 'The Wanderer', spice: 2,
    pal: { bg: '#2E5E4E', ink: '#F3EBD8', acc: '#F2A541', card: '#12281F' }, pattern: 'waves',
    bio: 'Airport to trek to rooftop in one outfit and one bag. Layers that pack flat, colours that hide dust, and a duffle that has seen things.',
    moves: ['Layer for three temperatures', 'Earthy base, one bright accent', 'One bag that carries a whole day'],
    avoid: 'anything you cannot walk 10 km in',
    types: { duffle: 1, backpack: .9, tote: .6, crossbody: .6, shoulder: .3 }, tones: { olive: 1, black: .7, cream: .6 },
    favourites: ['grapevine-utility-duffle', 'undertone-olive-leather-backpack', 'whisper-multi-pocket-backpack'],
    laneFn: (d, m) => Math.max(0, Math.min(1, .25 + (m.warmShare > .4 ? .2 : 0) + (m.colourfulness < 45 ? .15 : 0))),
    open: ['Namaste from somewhere with bad Wi-Fi. Let us talk about this fit.', 'Good travel energy. Now make it survive a day.', 'I like it. Could you walk ten kilometres in it though?'],
    close: ['Pack light, look sharp.', 'See you at the next gate.', 'Adventure is an outfit too.'],
    voice: 'Chill traveller vlogger voice, warm, practical, a bit poetic about places, talks about layers, packing, airports, treks. Light Hinglish.',
  },
  {
    id: 'kabir', lane: 'internet boyfriend energy, soft tailoring, open collars, white shirts, subtle chains, a leather bag', props: ['rose', 'envelope', 'heart', 'shades'], unlock: 4, loading: ['Crush Kabir is writing you a note…', 'Crush Kabir is picking a playlist…'], photo: null,
    name: 'Crush Kabir', role: 'The Internet Crush', spice: 3,
    pal: { bg: '#8B0F2A', ink: '#FFE9E3', acc: '#FFB199', card: '#3A0612' }, pattern: 'lines',
    bio: 'The one everyone saved to their close friends. Open collar, one thin chain, sleeves rolled once, and a bag that looks like it has love letters in it.',
    moves: ['Unbutton one, roll the sleeves once', 'One thin chain, nothing more', 'A soft leather bag, carried not slung'],
    avoid: 'trying too hard',
    types: { shoulder: 1, tote: .8, crossbody: .7, backpack: .4, duffle: .3 }, tones: { black: .9, cream: .8, olive: .6 },
    favourites: ['innuendo-slouch-shoulder-bag', 'gossipmonger-structured-tote', 'open-secret-canvas-tote'],
    laneFn: (d, m) => Math.max(0, Math.min(1, .25 + (m.hues <= 2 ? .2 : 0) + (m.dark ? .1 : .05))),
    open: ['Hey. Do not panic, this is a good start.', 'I would text back for this fit. Almost.', 'Soft launch energy. Let us make it a hard launch.'],
    close: ['Now go be someone’s crush.', 'Effortless takes effort. You got it.', 'Send me a pic after.'],
    voice: 'Charming, warm, flirty-but-respectful internet-boyfriend voice, calm and confident, a little poetic, light Hinglish. Talks about effortless polish, open collars, thin chains, leather.',
  },
];

export const byId = Object.fromEntries(STYLISTS.map(s => [s.id, s]));