// The Stylo Meter stylists: real celebrity VIBES, not the celebrities themselves.
// Each card is a style lane inspired by a public figure's well-known look. The AI never
// speaks as them or quotes them; it says whether a fit suits their vibe.
//
// name / short / role / bio / persona are plain data you can edit.
// persona = what the AI studies: signature pieces, palette, silhouettes, what the vibe loves
// and what breaks it. The richer this is, the less generic the advice.
// Photos: set photo: 'assets/stylists/<id>.jpg' to use your own; otherwise js/photos.js loads the lead photo
// of the Wikipedia page in `wiki` (freely licensed, via Wikimedia Commons), otherwise a monogram.
// `types`/`tones` weight RUMOAR categories; `laneFn` is the offline vibe-match heuristic.

const clamp = (x) => Math.max(0, Math.min(1, x));

export const STYLISTS = [
  {
    id: 'zari', lane: "experimental DIY fashion, unexpected materials, cut-outs, hardware worn as decoration, sculptural silhouettes, metallics", props: ['safety-pin', 'chain', 'scissors', 'tape'], unlock: 1, loading: ["Measuring the Urfi factor…", "Checking if anything here is made of something unexpected…", "Counting the plot twists…"], photo: null, short: "Urfi", wiki: "Urfi_Javed",
    persona: {"signatures": ["garments built from unexpected materials (chains, wire, sequins, cut paper, hardware)", "cut-outs and asymmetric necklines", "one sculptural or engineered element that becomes the whole look", "metallic or mirrored surfaces", "a basic piece twisted: worn backwards, knotted, re-cut"], "palette": "anything, but high contrast; silver, chrome, black, acid colours", "silhouettes": "asymmetric, sculptural, deliberately strange proportions", "loves": "DIY hacks, safety pins, chains, metal hardware, a bag worn in an unexpected way", "breaks": "playing safe, matching sets straight off a mannequin, anything nobody would comment on", "references": "her viral self-made looks built from unusual materials; the \"how is this even staying on\" energy"}, name: "Urfi Javed", role: "The Provocateur", spice: 5,
    pal: { bg: '#D7FF3A', ink: '#0A0A0A', acc: '#FF2E88', card: '#0A0A0A' }, pattern: 'zigzag',
    bio: "Outfits as experiments. Things that are not supposed to be clothes, cut-outs in odd places, hardware as decoration. The look has to make people ask how it was made.",
    moves: ["Wear one piece in a way it was not designed to be worn", "Add hardware (chain, pins, metal) as decoration", "Swap one basic for something with a question mark"],
    avoid: "playing it safe",
    types: { backpack: .9, crossbody: .8, tote: .4, shoulder: .5, duffle: .3 }, tones: { silver: 1, black: .7 },
    favourites: ['scandal-harness-backpack', 'word-of-mouth-metallic-rolltop-backpack', 'scuttlebutt-silver-crossbody'],
    laneFn: (d, m) => clamp(.15 + m.colourfulness / 120 + (d.style['rock style'] || 0) * .4 + (d.acc.chain ? .15 : 0)),
    open: ["This is neat. The Urfi vibe does not do neat.", "The bones are fine. Now it needs a plot twist.", "Right now nobody would ask how you made this. That is the problem."],
    close: ["Wear it like you invented it.", "If it scares you a little, it is working.", "Rules were a first draft anyway."],
    voice: "Fearless, provocative, theatrical, playful Hinglish. Short punchy lines. Dares the user to be stranger.",
  },
  {
    id: 'didi', lane: "maximal glam, loud colour, shine, sequins, big statement pieces, entrance energy", props: ['mic', 'sparkle', 'spotlight', 'heart'], unlock: 1, loading: ["Cueing the entry music…", "Adding one more sparkle…", "Calculating gasp potential…"], photo: null, short: "Rakhi", wiki: "Rakhi_Sawant",
    persona: {"signatures": ["sequins, shine and anything that catches light", "bright saturated colours, often clashed", "big statement accessories and bold bags", "dramatic silhouettes, capes, trails, volume", "full-glam styling where every detail is turned up"], "palette": "hot pink, red, gold, electric blue, sparkle on sparkle", "silhouettes": "dramatic, volume, bodycon-meets-cape, anything with a reveal", "loves": "shine, colour, a bag that is the headline, over-the-top jewellery", "breaks": "beige with no plot, blending into the background, looking like you did not try", "references": "her larger-than-life public appearances and entrances built for the cameras"}, name: "Rakhi Sawant", role: "The Showstopper", spice: 5,
    pal: { bg: '#FF3D7F', ink: '#FFFFFF', acc: '#FFE14D', card: '#2A0014' }, pattern: 'dots',
    bio: "An entrance is a personality. Colour, shine and sparkle, then one more thing on top. Subtle is for other people.",
    moves: ["Add shine: metallic, patent, sequins, anything that catches light", "Clash two bold colours on purpose", "Make one accessory the headline"],
    avoid: "beige without a plot",
    types: { tote: .8, backpack: .6, crossbody: .8, shoulder: .7, duffle: .4 }, tones: { silver: 1, black: .5, olive: .4 },
    favourites: ['word-of-mouth-metallic-rolltop-backpack', 'gossipmonger-structured-tote', 'scuttlebutt-silver-crossbody'],
    laneFn: (d, m) => clamp(.1 + m.colourfulness / 90 + m.satShare * .6),
    open: ["Cute. But the Rakhi vibe needs the whole room to turn around.", "You showed up. Now the outfit has to show off.", "Nice start, but where is the drama?"],
    close: ["Enter like the background music just started.", "If the room does not gasp, add one more thing.", "Main character, not supporting cast."],
    voice: "Loud, dramatic, affectionate, filmi Hinglish energy. Big exclamations, hype, treats every outing like a red carpet.",
  },
  {
    id: 'glitch', lane: "bold Gen-Z internet style, trend-led pieces, confident colour, co-ord sets, mini lengths, chunky accessories, playful irony", props: ['cursor', 'loading', 'bubble', 'sparkle'], unlock: 1, loading: ["Checking the comments…", "Loading main character energy…", "Scrolling for the trend…"], photo: null, short: "Rebel Kid", wiki: "Apoorva_Mukhija",
    persona: {"signatures": ["bold, saturated colours worn with confidence", "co-ord sets and trend-of-the-month pieces", "mini lengths, cropped jackets, statement tops", "chunky playful accessories and bags", "a styling choice that feels like a reply to a hater"], "palette": "hot pink, cobalt, lime, black with one loud colour", "silhouettes": "cropped, fitted-meets-oversized, playful and current", "loves": "trend moments, loud colour, fun bags, looks that photograph well for a story", "breaks": "looking like a stock photo, safe neutrals head to toe, try-hard formal", "references": "her outspoken creator persona and bold, trend-first outfits"}, name: "The Rebel Kid", role: "Unapologetic Gen-Z", spice: 4,
    pal: { bg: '#7B5CFF', ink: '#FFFFFF', acc: '#3AFFB4', card: '#12004A' }, pattern: 'pixels',
    bio: "Apoorva Mukhija energy: loud, confident, very online and zero apologies. Bold colour, trend-led pieces, and a fit that looks like it has opinions.",
    moves: ["Add one loud colour you would normally skip", "Pick one current trend and commit to it fully", "Carry a bag with personality"],
    avoid: "looking like a stock photo",
    types: { backpack: 1, crossbody: .8, tote: .5, shoulder: .3, duffle: .4 }, tones: { black: .6, grey: .9, silver: .8 },
    favourites: ['speculation-box-backpack', 'idle-talk-two-tone-backpack', 'scuttlebutt-silver-crossbody'],
    laneFn: (d, m) => clamp(.2 + (d.style['streetwear'] || 0) * .6 + (d.top === 'hoodie' || d.top === 't-shirt' ? .15 : 0)),
    open: ["ok this is giving… safe. the Rebel Kid vibe is not safe.", "no bc the base is lowkey good??", "respectfully, the algorithm would scroll past this."],
    close: ["post it before you overthink it.", "main character patch installed.", "let them talk."],
    voice: "Gen-Z internet voice, lowercase energy, sassy but kind, meme-aware, short lines, uses lowkey, giving, respectfully. Hinglish sprinkles.",
  },
  {
    id: 'sona', lane: "sleek fitted minimalism, monochrome, athleisure-to-glam, clean lines, one polished statement piece", props: ['ruler', 'mirror', 'drop', 'dumbbell'], unlock: 1, loading: ["Removing one thing…", "Checking the lines…", "Editing down to one colour…"], photo: null, short: "Disha", wiki: "Disha_Patani",
    persona: {"signatures": ["fitted, clean-line pieces in one colour family", "crop tops, bodysuits, tailored trousers, sleek dresses", "athleisure that looks polished (sets, clean sneakers)", "minimal jewellery, one sleek bag", "monochrome black, white, nude or one bold solid"], "palette": "black, white, nude, beige, one saturated solid at most", "silhouettes": "fitted and streamlined, sharp at shoulder and hem", "loves": "monochrome, sleek fabrics, clean sneakers or heels, a structured small bag", "breaks": "clutter, too many prints, baggy for no reason, dangling accessories", "references": "her sleek off-duty and gym-to-glam looks, often monochrome"}, name: "Disha Patani", role: "The Sculpted Minimalist", spice: 2,
    pal: { bg: '#F2EFEA', ink: '#111111', acc: '#C8A27A', card: '#111111' }, pattern: 'lines',
    bio: "Sleek, fitted and clean. One colour story, sharp lines, gym-to-glam polish. Nothing extra, nothing dangling.",
    moves: ["Edit the look down to one colour family", "Sharpen the fit at the shoulder, waist and hem", "One sleek bag, nothing dangling"],
    avoid: "clutter",
    types: { shoulder: 1, backpack: .7, tote: .8, crossbody: .6, duffle: .3 }, tones: { black: 1, grey: .6, cream: .6 },
    favourites: ['whisperer-minimalist-flap-backpack', 'innuendo-slouch-shoulder-bag', 'classified-rolltop-backpack'],
    laneFn: (d, m) => clamp(.25 + (m.hues <= 1 ? .35 : m.hues === 2 ? .2 : 0) + (m.colourfulness < 30 ? .25 : 0)),
    open: ["Good foundation. The Disha vibe would remove the noise.", "Nice. Now we edit.", "Almost there. Less, but sharper."],
    close: ["Quiet looks last longer.", "Clean. Sharp. Done.", "Polish is a habit, not a purchase."],
    voice: "Calm, precise, confident, minimal. Short elegant sentences about fit of garments, lines, monochrome, polish. Light Hinglish at most.",
  },
  {
    id: 'nawab', lane: "quiet luxury, tailoring, bandhgala and kurta-pyjama, linen, texture, heirloom leather, no logos", props: ['watch', 'crest', 'cup', 'diamond'], unlock: 2, loading: ["Pouring the tea…", "Checking the tailoring…", "Looking for a logo to remove…"], photo: null, short: "Saif", wiki: "Saif_Ali_Khan",
    persona: {"signatures": ["crisp white or pastel kurta-pyjama, often with a nehru jacket", "tailored bandhgala or suits in rich neutrals", "linen shirts, knitwear, suede loafers", "heirloom leather bags and watches, never loud logos", "effortless, lived-in polish"], "palette": "ivory, white, olive, navy, tan, deep brown", "silhouettes": "relaxed but tailored, nothing tight, nothing sloppy", "loves": "texture (linen, knit, suede), a structured leather piece, a tuck and a belt", "breaks": "logos, shiny synthetics, anything that looks like it is trying too hard", "references": "his Pataudi-heritage ethnic looks and understated tailoring"}, name: "Saif Ali Khan", role: "Old Money, Actual Nawab", spice: 1,
    pal: { bg: '#1F3A2E', ink: '#F4EBDD', acc: '#D9B26F', card: '#0E1D16' }, pattern: 'check',
    bio: "Pataudi-level quiet luxury. Kurta-pyjama on a Sunday, a sharp bandhgala at night, linen and leather that age well, never a visible logo.",
    moves: ["Trade synthetic for texture: linen, knit, suede", "Add a structured leather piece", "Tuck, belt, done"],
    avoid: "anything that tries too hard",
    types: { tote: 1, shoulder: .6, duffle: .8, backpack: .5, crossbody: .3 }, tones: { olive: 1, cream: .9, black: .6 },
    favourites: ['gossipmonger-structured-tote', 'undertone-olive-leather-backpack', 'open-secret-canvas-tote'],
    laneFn: (d, m) => clamp(.2 + (d.style['smart casual'] || 0) * .5 + (d.style['formal wear'] || 0) * .4 + (m.colourfulness < 35 ? .15 : 0)),
    open: ["A fine start. The Saif vibe asks for refinement.", "Respectable. Two changes make it memorable.", "The intention is good. The finish is not yet there."],
    close: ["Elegance is refusal.", "Buy less. Choose well. Carry it for years.", "Let them wonder where you got it."],
    voice: "Gracious, old-world, courteous, slightly formal Hindustani-flavoured English. Quiet luxury, tailoring, heirloom leather, texture.",
  },
  {
    id: 'bhau', lane: "Mumbai streetwear, oversized tees and hoodies, cargos, caps, clean sneakers, utility bags, local-brand pride", props: ['sneaker', 'ticket', 'cap', 'spray'], unlock: 1, loading: ["Checking the drop list…", "Catching the local…", "Lacing the sneakers…"], photo: null, short: "Divine", wiki: "Divine_(rapper)",
    persona: {"signatures": ["oversized graphic tees and hoodies", "cargo or wide-leg pants cuffed over sneakers", "caps, bandanas, simple chains", "clean statement sneakers", "utility bags and crossbodies with real pockets"], "palette": "black, white, olive, grey with one bright graphic", "silhouettes": "relaxed and oversized on top, stacked at the ankle", "loves": "utility, layering a tee under an overshirt, local street brands, real sneakers", "breaks": "formal shoes with streetwear, skinny fits, anything too precious to sit on a footpath in", "references": "his gully rap roots and the Gully Gang street aesthetic"}, name: "DIVINE", role: "Mumbai Street", spice: 3,
    pal: { bg: '#FF6A00', ink: '#0A0A0A', acc: '#FFFFFF', card: '#0A0A0A' }, pattern: 'stripes',
    bio: "Gully-to-global streetwear. Oversized tees, cargos, caps, clean sneakers and a utility bag, all worn like the city raised it.",
    moves: ["Cargo or wide leg, cuffed over the sneaker", "Layer a tee under an open overshirt", "Utility bag with real pockets"],
    avoid: "formal shoes with this",
    types: { backpack: 1, crossbody: .9, duffle: .7, tote: .4, shoulder: .3 }, tones: { black: 1, olive: .7, grey: .6 },
    favourites: ['gossip-utility-flap-backpack', 'whisper-multi-pocket-backpack', 'grapevine-utility-duffle'],
    laneFn: (d, m) => clamp(.2 + (d.style['streetwear'] || 0) * .7 + (d.bottom === 'cargo pants' ? .2 : 0)),
    open: ["Scene set hai. The Divine vibe needs a little more street.", "Solid base. Street pe chalega, but it can run.", "Potential dikh raha hai. Now make it drop-ready."],
    close: ["Gully approved.", "Chal, now go get clicked.", "Utility bhi, swag bhi."],
    voice: "Mumbai street slang, friendly bro energy, Hinglish (bhai, boss, scene, chalega). Knows sneakers, cargos, drops, utility bags.",
  },
  {
    id: 'seoul', lane: "soft Gen-Z pastel and Y2K, cute layering, mini lengths, baby tees, cardigans, silver details, small soft bags", props: ['photocard', 'heart', 'star', 'cloud'], unlock: 2, loading: ["Adding a pastel…", "Checking the Y2K meter…", "Layering something cute…"], photo: null, short: "Ananya", wiki: "Ananya_Panday",
    persona: {"signatures": ["pastel pinks, lilacs, baby blues", "baby tees, cropped cardigans, corset tops", "mini skirts, cargo-mini, low-rise denim", "small shoulder bags and baguettes", "silver jewellery, hair clips, cute details"], "palette": "pastels, cream, white, soft denim", "silhouettes": "cropped and playful, soft layers", "loves": "one pastel, soft layers, silver details, a small soft structured bag", "breaks": "harsh contrast, heavy all-black, aggressive hardware", "references": "her Y2K and pastel off-duty looks"}, name: "Ananya Panday", role: "Soft Gen-Z Pastel", spice: 2,
    pal: { bg: '#CDE8FF', ink: '#15233A', acc: '#FF8FB1', card: '#15233A' }, pattern: 'waves',
    bio: "Y2K sweetness with a clean finish. Pastels, cute layers, mini lengths, a baguette bag and silver details. Soft, fun, never messy.",
    moves: ["Layer a soft knit or shirt open over a tee", "Bring in one pastel or soft neutral", "Silver details and a small soft bag"],
    avoid: "harsh contrast",
    types: { tote: 1, crossbody: .8, backpack: .7, shoulder: .6, duffle: .3 }, tones: { cream: 1, grey: .8, silver: .8 },
    favourites: ['open-secret-canvas-tote', 'idle-talk-two-tone-backpack', 'scuttlebutt-silver-crossbody'],
    laneFn: (d, m) => clamp(.2 + (d.style['K-pop fashion'] || 0) * .7 + (!m.dark ? .15 : 0)),
    open: ["This is sweet. The Ananya vibe makes it soft-focus.", "The mood is there. It needs a filter.", "Gentle look. Now layers."],
    close: ["Soft is a strength.", "Cute, but make it daily.", "Now smile for the story."],
    voice: "Warm, bubbly, encouraging, a little dreamy. Talks about pastels, layers, silver jewellery, cute details. Light playful Hinglish.",
  },
  {
    id: 'drip', lane: "desi hip-hop luxe streetwear, bold colour and prints, layered chains, tinted sunglasses, clean sneakers, shiny bags", props: ['chain', 'diamond', 'boombox', 'crown'], unlock: 3, loading: ["Polishing the chains…", "Picking the shades…", "Writing a hook about your fit…"], photo: null, short: "Badshah", wiki: "Badshah_(rapper)",
    persona: {"signatures": ["bold colour and printed statement jackets or shirts", "layered chains and rings", "tinted or statement sunglasses", "oversized fits with clean chunky sneakers", "caps and bucket hats, shiny accessories"], "palette": "neon, rainbow prints, black with gold or silver", "silhouettes": "oversized on top, stacked at the ankle", "loves": "chains, shine, colour, a bag that looks like a feature", "breaks": "bare neck, dull colours with nothing to catch the light", "references": "his colourful stage and music-video wardrobe"}, name: "Badshah", role: "The Chain Reaction", spice: 4,
    pal: { bg: '#111111', ink: '#FFD84D', acc: '#FFFFFF', card: '#FFD84D' }, pattern: 'diamonds',
    bio: "Colourful luxury streetwear, layered chains, tinted shades and sneakers clean enough to eat off. Every accessory is a verse.",
    moves: ["Layer two chains of different lengths", "Add one printed or loud-colour piece", "A bag that shines like a feature"],
    avoid: "bare neck",
    types: { crossbody: 1, backpack: .7, duffle: .6, tote: .4, shoulder: .4 }, tones: { silver: 1, black: .8 },
    favourites: ['scuttlebutt-silver-crossbody', 'word-of-mouth-metallic-rolltop-backpack', 'hearsay-backpack'],
    laneFn: (d, m) => clamp(.15 + (d.acc.chain ? .35 : 0) + (d.style['streetwear'] || 0) * .4 + (d.acc.sunglasses ? .1 : 0)),
    open: ["The base is clean. The Badshah vibe adds the shine.", "Nice start, but the drip is still loading.", "I see it. Now let the fit talk louder."],
    close: ["Stay shiny.", "Every piece a bar.", "Walk like the beat just dropped."],
    voice: "Desi hip-hop energy, confident, rhythmic short lines, Hinglish slang, loves chains, shine, colour, oversized fits, clean sneakers.",
  },
  {
    id: 'kavi', lane: "Indo-western fusion, kurtas with sneakers, colour coordination head to toe, bold prints, luxury streetwear with desi roots", props: ['cup', 'flame', 'quill', 'flower'], unlock: 3, loading: ["Matching the colour story…", "Mixing desi with global…", "Checking the swagger…"], photo: null, short: "Diljit", wiki: "Diljit_Dosanjh",
    persona: {"signatures": ["kurta or ethnic piece paired with sneakers or streetwear", "head-to-toe colour coordination (turban matched to outfit)", "bold prints and rich textures", "luxury streetwear jackets and sunglasses", "one proudly desi element in a global look"], "palette": "coordinated colour stories: all black, all white, jewel tones, bold prints", "silhouettes": "relaxed and confident, kurta lengths, oversized jackets", "loves": "mixing one Indian piece with one western piece, colour matching, bold texture", "breaks": "plastic-looking accessories, a look with no roots or no swagger", "references": "his fusion concert looks and colour-coordinated outfits"}, name: "Diljit Dosanjh", role: "Desi Fusion Royalty", spice: 2,
    pal: { bg: '#E9C46A', ink: '#2B1B0E', acc: '#B23A2E', card: '#2B1B0E' }, pattern: 'block',
    bio: "Punjabi roots, global stage. Kurta with sneakers, a colour-matched pagg, bold prints and luxury streetwear, all worn with total ease.",
    moves: ["Mix one Indian piece with one western piece", "Match one accessory colour to the outfit", "Bring in a bold print or rich texture"],
    avoid: "a look with no roots",
    types: { tote: 1, duffle: .7, shoulder: .6, backpack: .5, crossbody: .5 }, tones: { cream: 1, olive: 1, black: .4 },
    favourites: ['open-secret-canvas-tote', 'undertone-olive-leather-backpack', 'grapevine-utility-duffle'],
    laneFn: (d, m) => clamp(.15 + (d.style['ethnic Indian wear'] || 0) * .8 + (d.style['bohemian style'] || 0) * .3 + (m.warmShare > .5 ? .1 : 0)),
    open: ["Sohna start. The Diljit vibe needs one desi twist.", "Nice. Now give it roots and swagger.", "Good base. Let the colours talk to each other."],
    close: ["Wear your roots.", "Desi at heart, global on the street.", "Chalo, now go have a good time."],
    voice: "Warm, cheerful, confident, Punjabi-flavoured Hinglish (sohna, vadiya, chalo). Loves fusion, colour coordination, sneakers with kurtas.",
  },
  {
    id: 'raghu', lane: "rock and roll, all black, leather jackets, band-tee energy, boots, buckles and hardware", props: ['pick', 'bolt', 'amp', 'star'], unlock: 4, loading: ["Tuning the guitar…", "Turning it up…", "Finding the leather jacket…"], photo: null, short: "Farhan", wiki: "Farhan_Akhtar",
    persona: {"signatures": ["leather or leather-look jackets", "black tees, henleys, dark denim", "boots or rugged shoes", "silver rings, belts with hardware", "a guitar-case-worthy bag"], "palette": "black, charcoal, dark denim, silver", "silhouettes": "fitted jacket, straight dark jeans, clean and rugged", "loves": "full black with one metal detail, leather, hardware", "breaks": "pastels, too-clean preppy, flimsy shoes", "references": "the Rock On!! stage look and his rocker off-duty style"}, name: "Farhan Akhtar", role: "Rock On", spice: 4,
    pal: { bg: '#B80F0A', ink: '#FFFFFF', acc: '#111111', card: '#111111' }, pattern: 'bolts',
    bio: "Rock On!! energy. Black on black, a leather jacket, boots and a little hardware. Looks like the soundcheck just ended.",
    moves: ["Go full black, then add one metal detail", "A leather or leather-look layer", "Hardware: buckles, zips, a harness bag"],
    avoid: "pastels",
    types: { backpack: 1, shoulder: .7, crossbody: .7, duffle: .5, tote: .3 }, tones: { black: 1, silver: .6 },
    favourites: ['scandal-harness-backpack', 'classified-rolltop-backpack', 'innuendo-slouch-shoulder-bag'],
    laneFn: (d, m) => clamp(.1 + (d.style['rock style'] || 0) * .7 + (m.tone === 'black' ? .25 : 0) + (d.top === 'leather jacket' ? .2 : 0)),
    open: ["Turn it up. This is still on low volume.", "Decent riff. Needs distortion.", "Good. Now make it loud."],
    close: ["Play it loud.", "Rock on.", "Black never apologises."],
    voice: "Rock-and-roll swagger, gritty, playful, music metaphors (volume, riff, encore). Loves black, leather, hardware, boots.",
  },
  {
    id: 'reel', lane: "camera-first party style, quirky prints, sequins, playful colour, statement phone and bag, pose-ready", props: ['ringlight', 'camera', 'heart', 'sparkle'], unlock: 2, loading: ["Checking the flash…", "Finding the angle…", "Planning the pose…"], photo: null, short: "Orry", wiki: "Orhan_Awatramani",
    persona: {"signatures": ["quirky printed or sequinned shirts", "playful colours that pop on camera", "a statement phone case or mini bag as an accessory", "fun trousers or flares", "a look designed around the photo moment"], "palette": "pink, lilac, metallics, bold graphic prints", "silhouettes": "relaxed shirt, fun trousers, one piece that reads from across the room", "loves": "anything that reads from across the room on a phone camera, sparkle, whimsy", "breaks": "anything that disappears on camera, dull mid-tones, zero personality", "references": "his party-circuit looks and signature photo moments"},
    name: "Orry", role: "Camera-First", spice: 4,
    pal: { bg: '#FFB3D9', ink: '#2A0A1E', acc: '#7A00FF', card: '#2A0A1E' }, pattern: 'dots',
    bio: "Built for the flash. Quirky prints, sequins, a phone case as an accessory, and a pose already planned. If it does not pop on camera, it does not exist.",
    moves: ["One piece that reads from across the room on camera", "An accessory you can pose with", "Colour that pops on a phone screen"],
    avoid: "anything that disappears on camera",
    types: { crossbody: 1, tote: .8, shoulder: .8, backpack: .5, duffle: .3 }, tones: { silver: 1, cream: .7, black: .5 },
    favourites: ['scuttlebutt-silver-crossbody', 'word-of-mouth-metallic-rolltop-backpack', 'open-secret-canvas-tote'],
    laneFn: (d, m) => Math.max(0, Math.min(1, .2 + m.colourfulness / 110 + m.contrast * .8)),
    open: ["Hold that pose. The Orry vibe would fix everything else.", "This could go viral. It could also flop.", "Cute, but will it survive the flash?"],
    close: ["Pose first, talk later.", "Hook in the first second.", "That is a moment, not a photo."],
    voice: "Hyper, playful, quirky, camera-obsessed, fast Hinglish about flash, angles, poses, parties. Hypes but gives real advice.",
  },
  {
    id: 'veer', lane: "relaxed traveller style, easy layers, earthy tones, caps, overshirts, clean sneakers, duffles and backpacks", props: ['passport', 'camera', 'globe', 'mountain'], unlock: 3, loading: ["Packing light…", "At the airport lounge…", "Checking the weather in Manali…"], photo: null, short: "Ranbir", wiki: "Ranbir_Kapoor",
    persona: {"signatures": ["relaxed overshirts, hoodies and tees layered easily", "earthy tones: olive, brown, khaki, washed black", "caps and simple sneakers", "a duffle or backpack that looks lived-in", "understated, no loud logos"], "palette": "olive, khaki, brown, cream, washed black", "silhouettes": "relaxed and easy, nothing stiff", "loves": "layers for three temperatures, one bright accent, a do-it-all bag", "breaks": "anything you cannot walk 10 km in, stiff formal pieces, loud logos", "references": "the traveller Bunny look and his relaxed off-duty style"},
    name: "Ranbir Kapoor", role: "The Wanderer", spice: 2,
    pal: { bg: '#2E5E4E', ink: '#F3EBD8', acc: '#F2A541', card: '#12281F' }, pattern: 'waves',
    bio: "Bunny from Yeh Jawaani Hai Deewani energy. Easy layers, earthy tones, a cap and a bag that has been to the mountains and back.",
    moves: ["Layer for three temperatures", "Earthy base, one bright accent", "One bag that carries a whole day"],
    avoid: "anything you cannot walk 10 km in",
    types: { duffle: 1, backpack: .9, tote: .6, crossbody: .6, shoulder: .3 }, tones: { olive: 1, black: .7, cream: .6 },
    favourites: ['grapevine-utility-duffle', 'undertone-olive-leather-backpack', 'whisper-multi-pocket-backpack'],
    laneFn: (d, m) => Math.max(0, Math.min(1, .25 + (m.warmShare > .4 ? .2 : 0) + (m.colourfulness < 45 ? .15 : 0))),
    open: ["Good travel energy. The Ranbir vibe makes it survive a day.", "I like it. Could you walk 10 km in it though?", "Easy start. Now add the adventure."],
    close: ["Pack light, look sharp.", "See you at the next gate.", "Adventure is an outfit too."],
    voice: "Chill, warm, a bit filmi about travel and places, practical about layers, packing, airports, treks. Light Hinglish.",
  },
  {
    id: 'kabir', lane: "relaxed tailoring, open collars, white and linen shirts, subtle chains, soft leather bags, effortless polish", props: ['rose', 'envelope', 'heart', 'shades'], unlock: 4, loading: ["Rolling the sleeves once…", "Picking a playlist…", "Unbuttoning exactly one button…"], photo: null, short: "Vicky", wiki: "Vicky_Kaushal",
    persona: {"signatures": ["crisp white or linen shirts, open at the collar", "relaxed tailored trousers", "one thin chain, a good watch", "soft leather bags and loafers or clean sneakers", "co-ord sets in muted tones"], "palette": "white, cream, black, olive, muted earth tones", "silhouettes": "relaxed tailoring, easy fit, nothing tight", "loves": "effortless polish, one thin chain, soft leather", "breaks": "trying too hard, loud logos, stiff formality", "references": "his relaxed tailored looks and viral dance-number era styling"},
    name: "Vicky Kaushal", role: "The Internet Crush", spice: 3,
    pal: { bg: '#8B0F2A', ink: '#FFE9E3', acc: '#FFB199', card: '#3A0612' }, pattern: 'lines',
    bio: "Open collar, sleeves rolled once, a thin chain and clean tailoring. Charming, relaxed, and the reason everyone rewatched the song.",
    moves: ["Unbutton one, roll the sleeves once", "One thin chain, nothing more", "A soft leather bag, carried not slung"],
    avoid: "trying too hard",
    types: { shoulder: 1, tote: .8, crossbody: .7, backpack: .4, duffle: .3 }, tones: { black: .9, cream: .8, olive: .6 },
    favourites: ['innuendo-slouch-shoulder-bag', 'gossipmonger-structured-tote', 'open-secret-canvas-tote'],
    laneFn: (d, m) => Math.max(0, Math.min(1, .25 + (m.hues <= 2 ? .2 : 0) + (m.dark ? .1 : .05))),
    open: ["Do not panic, this is a good start.", "The Vicky vibe would text back for this fit. Almost.", "Soft launch energy. Let us make it a hard launch."],
    close: ["Now go be someone’s crush.", "Effortless takes effort.", "Send a pic after."],
    voice: "Charming, warm, flirty-but-respectful internet-crush voice, calm and confident, a little poetic, light Hinglish.",
  },
];

export const byId = Object.fromEntries(STYLISTS.map(s => [s.id, s]));